name: Download and Save ISO on Commit

on:
  push:
    branches:
      - main  # Replace with the name of your main branch or the branch you want to trigger the workflow on

jobs:
  download-and-save-iso:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download ISO
      run: |
        mkdir -p iso
        wget https://ia903404.us.archive.org/31/items/nexus.-lite-os.-8.1.x-64/Nexus.LiteOS.8.1.x64.iso -O iso/Nexus.LiteOS.8.1.x64.iso

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: liteos-iso
        path: iso
